### PR TITLE
Fixed bug changing JsonConvert.DefaultSettings

### PR DESCRIPTION
**Pull request by eduardomb08**
The tool should not change the DefaultSettings function as it is a singleton instance, shared application wide. Changing it impacts the application using this library. 

PS: Ideally, this function would only be set at startup time by the application owner. Changing it during runtime would have to account for thread safety issues.

### CODE REVIEW

**Comment by Courela** [comment]
Agree, changing the default settings will impact every application, but the library must have its own settings.

**Comment by eduardomb08** [comment]
> Agree, changing the default settings will impact every application, but the library must have its own settings.

This PR can be approved/merge before you create a config for the library, right? In out case, the issue breaks the client application. Having the library fixed soon would be great.

**Comment by Courela** [comment]
I think so, it will always use DateParseHandling.None, but I don't think that is a problem.
I don't know what happens if you have JsonConvert.DefaultValues set... but I think the library is expecting DateParseHandling.None

**Comment by eduardomb08** [comment]
Any ETA on merging this PR?

**Pull request merged**
