### PR TITLE
Fix broken recursive calls

### PR DESCRIPTION
**Pull request by eduardomb08**
This fixes issue #141  .

### CODE REVIEW

**Comment by Courela** [comment]
This PR has the changes of #140, it should only contain the fix for #141.

**Review by Courela — CHANGES_REQUESTED** [review]
This PR has the changes of #140, it should only contain the fix for #141.

**Comment by eduardomb08** [comment]
@Courela , I reverted those changes in this branch. Sorry about that.

**Review by Courela — APPROVED** [review]

**Comment by eduardomb08** [comment]
Hi @Courela , any estimate on when this fix would be merged into the master branch?

**Comment by WorkMaze** [comment]
Hi , I have merged all the pending requests to the main branch. However, this one and 2 others (133 and 131) have some merge conflicts. Is it possible to make new pull requests with these conflicts resolved? 

I will merge them and publish a new version once resolved.

Thank you!

**Comment by Courela** [comment]
#131 and #133 are fixed.

**Comment by WorkMaze** [comment]
Thanks @Courela, I have merged them. @eduardomb08 - Is it possible for you to have a look at the conflicts in this pull request?

Thanks!

**Comment by eduardomb08** [comment]
@WorkMaze , @Courela conflicts resolved. All tests passing. Sorry for the huge delay.

**Pull request merged**
