### PR TITLE
Non static JUSTContext

### PR DESCRIPTION
**Pull request by Courela**
JUSTContext is now a non-static class that can be passed to Transform methods. Function's registration works the same as before.

JsonTransformer as a global JUSTContext, called "GlobalContext", that works for all calls of Transform methods.

### CODE REVIEW

**Comment by ericwood73** [comment]
Very nicely done.  I was working on something similar, but I like your solution better.  One thing I would like to see; however, is a object variable added to JUSTContext which can be set to the instance of an object on which we want to invoke the methods.  Then we could change ReflectionHelper InvokeCustomMethod to 
```
internal static object InvokeCustomMethod(MethodInfo methodInfo, object[] parameters, bool convertParameters = false, object instance = null)
        {
            if (instance == null && !methodInfo.IsStatic)
            {
                instance = Activator.CreateInstance(methodInfo.DeclaringType);
            }
```

**Comment by Courela** [comment]
Is your idea to have only one class to hold all the custom functions? That may not be the case in some scenarios where you want to reuse code that you already have, spread across your project. Also you can end up not using any custom function, making that instance useless.

**Comment by ericwood73** [comment]
Not necessarily.  With my proposed changes, if you specified the instance, then you could only have one class for instance methods per transform execution.  If you don't specify the instance you can have instance methods from several different classes and whether you do or do not specify the instance you can any number of static functions.  Using custom instance methods right now doesn't make a ton of sense because each function call will happen on a new instance.  I suppose you could do what I'm suggesting at registration time, so each method can be specified with an instance to call the method, it just complicates the storage and retrieval of the custom functions slightly.  However, in my case, I am always invoking transforms from a single instance that has all of the custom functions on it, so that is not needed.

**Comment by WorkMaze** [comment]
Hi @Courela , @ericwood73 . Thank you very much your contribution. I really appreciate it.

**Pull request merged**
